name: multi_vendor_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.6
  google_maps_flutter: ^2.6.0
  flutter_polyline_points: 2.0.0
  geolocator: 11.0.0
  geocoding: 3.0.0
  flutter_screenutil: 5.9.0
  google_fonts: ^6.2.1
  get: 4.6.6
  flutter_vector_icons: 2.0.0
  cached_network_image: 3.3.1
  flutter_rating_bar: 4.0.1
  flutter_hooks: ^0.21.0
  http: ^1.2.1
  shimmer: 3.0.0
  glass: 2.0.0+1
  flutter_svg: 2.0.10+1
  lottie: 3.1.0
  get_storage: 2.1.1
  webview_flutter: ^4.7.0
  webview_flutter_android: 3.16.0
  webview_flutter_wkwebview: ^3.13.0
  device_preview: 1.1.0
  otp_text_field: 1.1.3
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  country_picker: 2.0.25

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

